name: Rust

on:
  push:
    branches: [ cdsupina-dev ]
  pull_request:
    branches: [ cdsupina-dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
